[package]
name = "uiua-docs-generator"
version = "0.14.0"
edition = "2021"

[dependencies]
uiua = { path = "../uiua" }
clap = "4.5.20"
thiserror = "1.0.65"
same-file = "1.0.6"
leptos = { version = "0.6.15", features = ["serde", "csr"] }
kuchiki = "0.8.1"
markdown = "1.0.0-alpha.21"
html5ever = "0.29.0"
markup5ever = "0.10.1"

[profile.dev]
opt-level = 1